require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'helpmefund' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  pod 'react-native-fingerprint-scanner', :path => '../node_modules/react-native-fingerprint-scanner'

  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-viewpager', :path => '../node_modules/@react-native-community/viewpager'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'helpmefundTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'helpmefund-tvOS' do
  # Pods for helpmefund-tvOS

  target 'helpmefund-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
